#!/bin/bash

cd ~

echo "Stopping processes"
forever stopall

echo "Deleting all logfiles"
forever cleanlogs

echo "Deleting analysis directories"
cd /home/ubuntu/Shared/Workspace/
rm -rf Analysis_Node1
mkdir Analysis_Node1

cd /home/ubuntu/Shared2/Workspace/
rm -rf Analysis_Node2
mkdir Analysis_Node2

echo "Starting Analysis Client"
cd ~/analysis_client
rm /logs/analysis.log
forever start -l /logs/analysis.log client.js

echo "Starting Cloud Watch"
node run setCloudWatchAlarm
